kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-data-pv
  namespace: weilus-base
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jenkins-data-pv
  nfs:
    path: /data/nfs-k8s/jenkins/data
    server: 192.168.1.38
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-data-pvc
  namespace: weilus-base
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: jenkins-data-pv
---
kind: Service
apiVersion: v1
metadata:
  name: jenkins
  namespace: weilus-base
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32766  # 30000 - 32767
  type: NodePort
  selector:
    app: jenkins
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: jenkins
  namespace: weilus-base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      name: jenkins
      namespace: weilus-base
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: registry.cn-hangzhou.aliyuncs.com/weilus923/jenkins:2.180
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jenkins-data
          mountPath: /var/jenkins_home
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: kubectl-bin
          mountPath: /usr/bin/kubectl
        - name: kubectl-conf
          mountPath: /root/.kube/config
      volumes:
      - name: jenkins-data
        persistentVolumeClaim:
          claimName: jenkins-data-pvc
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: kubectl-bin
        hostPath:
          path: /usr/bin/kubectl
      - name: kubectl-conf
        hostPath:
          path: /root/.kube/config