kind: Service
apiVersion: v1
metadata:
  name: solr
  namespace: solr-cloud
spec:
  ports:
  - port: 8983
    protocol: TCP
    targetPort: 8983
    nodePort: 32765  # 30000 - 32767
  type: NodePort
  selector:
    app: solr
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: solr
  namespace: solr-cloud
spec:
  serviceName: solr-service
  replicas: 4
  selector:
    matchLabels:
      app: solr
  template:
    metadata:
      name: solr
      namespace: solr-cloud
      labels:
        app: solr
    spec:
      containers:
      - name: solr
        image: solr:7.7-alpine
        imagePullPolicy: IfNotPresent
        env:
        - name: ZK_HOST
          value: 192.168.1.37:2181
        - name: solr.data.home
          value: /data/solrdata
        ports:
        - containerPort: 8983
        volumeMounts:
        - name: data
          mountPath: /data/solrdata
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: solr-data-pv
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi