apiVersion: v1
kind: Service
metadata:
  name: zk-cs
  namespace: weilus-base
spec:
  ports:
  - port: 2181
  selector:
    app: zookeeper
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: zookeeper
  namespace: weilus-base
spec:
  serviceName: zookeeper
  replicas: 3
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      name: zookeeper
      namespace: weilus-base
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: zookeeper:3.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        volumeMounts:
        - name: zookeeper-data
          mountPath: /data
        volumeMounts:
        - name: zookeeper-conf
          mountPath: /conf
  volumeClaimTemplates:
  - metadata:
      name: zookeeper-data
    spec:
      storageClassName: zk-pv
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 200Mi
  - metadata:
      name: zookeeper-conf
    spec:
      storageClassName: zk-pv
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Mi