kind: PersistentVolume
apiVersion: v1
metadata:
  name: zookeeper-data-pv
spec:
  capacity:
    storage: 300Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: zookeeper-data-pv
  nfs:
    path: /data/nfs-k8s/zookeeper/data
    server: 192.168.1.38
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zookeeper-data-pvc
  namespace: weilus-base
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
  storageClassName: zookeeper-data-pv
---
kind: Service
apiVersion: v1
metadata:
  name: zookeeper
  namespace: weilus-base
spec:
  ports:
  - port: 2181
    protocol: TCP
    targetPort: 2181
  clusterIP: 10.96.10.103
  selector:
    app: jenkins
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: zookeeper
  namespace: weilus-base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      name: zookeeper
      namespace: weilus-base
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: zookeeper:3.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181
        volumeMounts:
        - name: zookeeper-data
          mountPath: /data
      volumes:
      - name: zookeeper-data
        persistentVolumeClaim:
          claimName: zookeeper-data-pvc