apiVersion: v1
kind: Service
metadata:
  name: zk-hs
spec:
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: zk-cs
spec:
  ports:
  - port: 2181
    name: client
  selector:
    app: zookeeper
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: zookeeper
  namespace: weilus-base
spec:
  serviceName: zookeeper
  replicas: 2
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      name: zookeeper
      namespace: weilus-base
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: zookeeper:3.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        volumeMounts:
        - name: zookeeper-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: zookeeper-data
    spec:
      storageClassName: zk-pv
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 300Mi