kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-zookeeper
  namespace: weilus-base
data:
  zoo.cfg: |-
      dataDir=/data
      dataLogDir=/datalog
      tickTime=2000
      initLimit=5
      syncLimit=2
      autopurge.snapRetainCount=3
      autopurge.purgeInterval=0
      maxClientCnxns=60
      standaloneEnabled=true
      admin.enableServer=true
      server.1=zookeeper-0:2888:3888;2181
      server.2=zookeeper-1:2888:3888;2181

---
apiVersion: v1
kind: Service
metadata:
  name: zk-cs
  namespace: weilus-base
spec:
  ports:
  - port: 2181
  selector:
    app: zookeeper
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: zookeeper
  namespace: weilus-base
spec:
  serviceName: zookeeper
  replicas: 2
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      name: zookeeper
      namespace: weilus-base
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: zookeeper:3.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181
        volumeMounts:
        - name: zookeeper-data
          mountPath: /data
        - name: zookeeper-conf
          mountPath: /conf
      volumes:
      - name: zookeeper-conf
        configMap:
          name: cm-zookeeper
  volumeClaimTemplates:
  - metadata:
      name: zookeeper-data
    spec:
      storageClassName: zk-pv
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 300Mi
