kind: PersistentVolume
apiVersion: v1
metadata:
  name: cloud-logs-pv
  namespace: weilus-base
spec:
  accessModes: ["ReadWriteMany","ReadOnlyMany"]
  storageClassName: cloud-logs-pv
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  nfs:
    path: /data/nfs-k8s/logs
    server: 192.168.1.38
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fluent-log-read-pvc
  namespace: weilus-base
spec:
  accessModes: ["ReadOnlyMany"]
  storageClassName: cloud-logs-pv
  resources:
    requests:
      storage: 1Gi