kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-fluentd
  namespace: weilus-base
data:
  fluent.conf: |-
      # Example:
      # 2015-12-21 23:17:22,066 [salt.state       ][INFO    ] Completed state [net.ipv4.ip_forward] at time 23:17:22.066081
      <source>
        @id gateway
        @type tail
        format /^(?<time>[^ ]* [^ ,]*)[^\[]*\[[^\]]*\]\[(?<level>[^ \]]*) *\] (?<message>.*)$/
        time_format %Y-%m-%d %H:%M:%S
        path /fluentd/log/gateway.log
        pos_file /fluentd/log/pos/gateway.pos
        tag gateway.log
      </source>

      <match gateway.log>
          @type elasticsearch
          host localhost
          port 9200
          flush_interval 10s
          index_name ${tag}-%Y.%m.%d
          type_name  ${tag}-%Y.%m.%d
          include_tag_key true
          tag_key @log_name
          <buffer tag, time>
             timekey 1h
          </buffer>
      </match>
