---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: zk-pv1
spec:
  storageClassName: zk-pv
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Mi
  hostPath:
    path: /data/zookeeper/data1
#  nfs:
#    path: /data/nfs-k8s/zookeeper/data1
#    server: 192.168.1.38
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: zk-pv2
spec:
  storageClassName: zk-pv
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 20Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/zookeeper/data2
#  nfs:
#    path: /data/nfs-k8s/zookeeper/data2
#    server: 192.168.1.38
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: zk-pv3
spec:
  storageClassName: zk-pv
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 20Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/zookeeper/data3
#  nfs:
#    path: /data/nfs-k8s/zookeeper/data3
#    server: 192.168.1.38
