---
kind: Deployment
apiVersion: apps/v1
metadata:
 labels:
   app: elasticsearch
   role: master
 name: elasticsearch-master
 namespace: ns-elastic
spec:
 replicas: 3
 revisionHistoryLimit: 10
 selector:
   matchLabels:
     app: elasticsearch
     role: master
 template:
   metadata:
     labels:
       app: elasticsearch
       role: master
   spec:
     imagePullSecrets:
     - name: docker-registry-key
     containers:
       - name: elasticsearch-master
         image: registry.cn-hangzhou.aliyuncs.com/weilus923/es-ik:6.2.2
         ports:
           - containerPort: 9200
           - containerPort: 9300
         env:
           - name: "cluster.name"
             value: "elasticsearch-cluster"
           - name: "discovery.zen.ping.unicast.hosts"
             value: "elasticsearch-discovery"
           - name: "node.master"
             value: "true"
           - name: "node.data"
             value: "false"
           - name: "ES_JAVA_OPTS"
             value: "-Xms128m -Xmx128m"
         securityContext:
           privileged: true
---