---
apiVersion: v1
kind: Service
metadata:
 name: elasticsearch-data-service
 namespace: ns-elastic
 labels:
   app: elasticsearch
   role: data
spec:
 ports:
   - port: 9200
     name: outer
   - port: 9300
     name: inner
 clusterIP: None
 selector:
   app: elasticsearch
   role: data
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
 labels:
   app: elasticsearch
   role: data
 name: es
 namespace: ns-elastic
spec:
 replicas: 2
 revisionHistoryLimit: 10
 selector:
   matchLabels:
     app: elasticsearch
 serviceName: elasticsearch-data-service
 template:
   metadata:
     labels:
       app: elasticsearch
       role: data
   spec:
     containers:
       - name: elasticsearch-data
         image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
         command: ["bash", "-c", "ulimit -l unlimited && sysctl -w vm.max_map_count=262144 && chown -R elasticsearch:elasticsearch /usr/share/elasticsearch/data && exec su elasticsearch config-ik.sh && exec su elasticsearch docker-entrypoint.sh"]
         ports:
           - containerPort: 9200
             protocol: TCP
           - containerPort: 9300
             protocol: TCP
         env:
           - name: "cluster.name"
             value: "elasticsearch-cluster"
           - name: "bootstrap.memory_lock"
             value: "true"
           - name: "discovery.zen.ping.unicast.hosts"
             value: "elasticsearch-discovery"
           - name: "node.master"
             value: "false"
           - name: "node.data"
             value: "true"
           - name: "ES_JAVA_OPTS"
             value: "-Xms512m -Xmx512m"
           - name: "remote_ext_dict"
             value: "http://example.com/ext.dic"
           - name: "remote_ext_stopwords"
             value: "http://example.com/ext_stop.dic"
         securityContext:
           privileged: true
         volumeMounts:
           - name: es-data
             mountPath: /usr/share/elasticsearch/data
 volumeClaimTemplates:
   - metadata:
       name: es-data
     spec:
       accessModes: ["ReadWriteOnce"]
       storageClassName: elasticsearch-pv-sc
       resources:
         requests:
           storage: 1Gi