---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-svn-auth
  namespace: weilus-base
data:
  authz: |-
      [/]
        liutaiq = rw
        * =

      [test1:/]
        liutaiq = rw
        * =

      [jik:/]
        liutaiq = rw
        * =

  passwd: |-
      liutaiq:$apr1$VUzQudMc$zWbyrB/o9Df7Zq05WbcFA1