---
kind: Service
apiVersion: v1
metadata:
  name: postgres
  namespace: weilus-cloud
spec:
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 32345  # 30000 - 32767
  type: NodePort
  clusterIP: 10.96.10.101
  selector:
    app: postgres
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres
  namespace: weilus-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      name: postgres
      namespace: weilus-cloud
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:11.4-alpine
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_USER
          value: "root"
        - name: POSTGRES_PASSWORD
          value: "weilus"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data-pvc
