---
kind: Service
apiVersion: v1
metadata:
  name: mongo
  namespace: weilus-cloud
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongo
  namespace: weilus-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongo
      namespace: weilus-cloud
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:3.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongo-data-pvc