kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-data-pv
  namespace: weilus-cloud
spec:
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: redis-data-pv
  nfs:
    path: /data/nfs-k8s/redis/data
    server: 192.168.1.38
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-data-pvc
  namespace: weilus-cloud
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: redis-data-pv
---
kind: Service
apiVersion: v1
metadata:
  name: redis
  namespace: weilus-cloud
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  clusterIP: 10.96.10.102
  selector:
    app: redis
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis
  namespace: weilus-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      name: redis
      namespace: weilus-cloud
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        command:
        - redis-server
        args:
        - --requirepass '123456'
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-data-pvc