---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-data-pv0
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes: ["ReadWriteOnce"]
  storageClassName: data-redis-pv
  capacity:
    storage: 200Mi
  nfs:
    path: /data/nfs-k8s/redis/data0
    server: 192.168.1.38
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-data-pv1
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes: ["ReadWriteOnce"]
  storageClassName: data-redis-pv
  capacity:
    storage: 200Mi
  nfs:
    path: /data/nfs-k8s/redis/data1
    server: 192.168.1.38
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-data-pv2
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes: ["ReadWriteOnce"]
  storageClassName: data-redis-pv
  capacity:
    storage: 200Mi
  nfs:
    path: /data/nfs-k8s/redis/data2
    server: 192.168.1.38
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-data-pv3
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes: ["ReadWriteOnce"]
  storageClassName: data-redis-pv
  capacity:
    storage: 200Mi
  nfs:
    path: /data/nfs-k8s/redis/data3
    server: 192.168.1.38
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-data-pv4
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes: ["ReadWriteOnce"]
  storageClassName: data-redis-pv
  capacity:
    storage: 200Mi
  nfs:
    path: /data/nfs-k8s/redis/data4
    server: 192.168.1.38
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-data-pv5
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes: ["ReadWriteOnce"]
  storageClassName: data-redis-pv
  capacity:
    storage: 200Mi
  nfs:
    path: /data/nfs-k8s/redis/data5
    server: 192.168.1.38