---
kind: Service
apiVersion: v1
metadata:
  name: redis-svc
  namespace: weilus-cloud
spec:
  ports:
  - port: 6379
    targetPort: 6379
  clusterIP: 10.96.10.102
  selector:
    app: redis
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: redis
  namespace: weilus-cloud
spec:
  replicas: 6
  serviceName: redis-svc
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      name: redis
      namespace: weilus-cloud
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        imagePullPolicy: IfNotPresent
        command:
        - redis-server
        args:
        - --requirepass '123456'
        - --cluster-enabled yes
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: data-redis-pv
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi